export const ENGLISH = [
  "The quick brown fox jumps over the lazy dog",
  "Practice makes perfect every single day",
  "Typing is a valuable skill in the modern world",
  "Never stop learning and improving yourself",
  "The sun sets in the west and rises in the east",
  "A journey of a thousand miles begins with a single step",
  "Stay focused on your goals and dreams",
  "Every moment is a fresh beginning in life",
  "The best time to plant a tree was twenty years ago",
  "Success is the sum of small efforts repeated daily",
  "Reading books expands your mind and vocabulary",
  "Technology changes the way we live and work",
  "Creativity is intelligence having fun",
  "The early bird catches the worm every morning",
  "Simple things often bring the greatest happiness",
  "Learning to code opens up endless possibilities",
  "A positive attitude makes a big difference",
  "The future belongs to those who prepare for it",
  "Good things come to those who work hard",
  "Every expert was once a beginner just like you",
  "Take a deep breath and type each word carefully",
  "Consistency matters more than perfection always",
  "The only way to do great work is to love what you do",
  "Small daily improvements lead to big results",
  "Your fingers will get faster with regular practice",
  "Mistakes are proof that you are trying your best",
  "The secret of getting ahead is getting started",
  "Believe in yourself and all that you are capable of",
  "Patience and persistence can achieve the impossible",
  "Type each word as it appears on the screen above",
  "Keep your eyes on the screen not on the keyboard",
  "Speed and accuracy will improve over time",
  "Focus on rhythm and flow while you type along",
  "Every keystroke brings you closer to mastery",
  "The journey of learning never truly ends at all",
  "Wake up each morning with a determined attitude",
  "Let your fingers dance across the keyboard today",
  "Turn your face to the sun and the shadows fall behind",
  "Act as if what you do makes a difference it does",
  "What lies behind us and before us are tiny matters",
  "The only limit to our realization of tomorrow is doubt",
  "Do what you can with all you have wherever you are",
  "It does not matter how slowly you go as long as you go",
  "Quality means doing it right when no one is looking",
  "In the middle of every difficulty lies opportunity",
  "The mind is everything what you think you become",
  "Nothing is impossible the word itself says I am possible",
  "Happiness is not something ready made it comes from action",
  "Life is what happens when you are busy making other plans",
  "Your time is limited so do not waste it living a borrowed life",
  "A smooth sea never made a skilled sailor",
  "The greatest glory in living lies not in never falling",
  "The way to get started is to quit talking and begin doing",
  "Life is what we make it always has been always will be",
  "The world is full of wonderful things you just have to see them",
  "Well done is better than well said every single time",
  "It always seems impossible until it is finally done",
  "Wherever you go go with all your heart and soul",
  "The only person you are destined to become is the person you decide to be",
  "Everything you have ever wanted is on the other side of fear",
  "Success usually comes to those who are too busy to be looking for it",
  "The only impossible journey is the one you never begin",
  "What we achieve inwardly will change outer reality",
  "Great minds discuss ideas average minds discuss events",
  "The best revenge is massive success every single day",
  "Do not watch the calendar just make every day count",
  "The unexamined life is not worth living at all",
  "To be yourself in a world that is constantly trying to change you is great",
  "He who has a why to live can bear almost any how",
  "Be yourself everyone else is already taken",
  "Two roads diverged in a wood and I took the one less traveled",
  "You miss one hundred percent of the shots you do not take",
  "The only thing we have to fear is fear itself",
  "That which does not kill us makes us stronger in the end",
  "In three words I can sum up everything I have learned about life it goes on",
  "Life is really simple but we insist on making it complicated",
  "The purpose of life is not to be happy it is to be useful",
  "Get busy living or get busy dying that is the choice",
  "Whether you think you can or think you cannot you are right",
  "The best way to predict the future is to create it yourself",
  "You must be the change you wish to see in the world",
  "It is during our darkest moments that we must focus to see the light",
  "Do not go where the path may lead go instead where there is no path",
  "We know what we are but know not what we may become next",
  "Try not to become a man of success but rather a man of value",
  "Success is not final failure is not fatal it is the courage to continue",
  "Imagination is more important than knowledge itself",
  "The important thing is not to stop questioning the universe",
  "Logic will get you from A to B imagination will take you everywhere",
  "Strive not to be a success but rather to be of great value",
  "The true sign of intelligence is not knowledge but imagination",
  "Learn from yesterday live for today hope for tomorrow always",
  "The difference between stupidity and genius is that genius has its limits",
  "A person who never made a mistake never tried anything new",
  "Any fool can know the point is to understand the bigger picture",
  "Life is like riding a bicycle to keep your balance you must keep moving",
  "The measure of intelligence is the ability to change your mind",
  "Science without religion is lame religion without science is blind",
  "Time is what we want most but what we use worst of all",
];

export const KOREAN = [
  "지금부터 천천히 한글 문장을 입력해보세요",
  "타자 연습은 꾸준함이 가장 중요합니다",
  "오늘도 좋은 하루 보내시길 바랍니다",
  "모든 위대한 일에는 작은 시작이 있습니다",
  "노력 없이 얻을 수 있는 결과는 없습니다",
  "컴퓨터 자판을 익히는 것은 생각보다 쉽습니다",
  "올바른 손가락 위치가 빠른 타자의 비결입니다",
  "천천히 정확하게 치는 것이 더 중요합니다",
  "자신의 타자 속도에 너무 연연하지 마세요",
  "매일 조금씩 연습하면 실력이 늘어납니다",
  "화면을 보면서 타자하는 습관을 길러보세요",
  "오타가 나도 괜찮습니다 계속 연습하세요",
  "한글 문서를 작성할 때 타자 실력이 빛을 발합니다",
  "올바른 자세로 앉아서 타자 연습을 해보세요",
  "손목에 무리가 가지 않도록 주의해야 합니다",
  "처음에는 느리더라도 포기하지 않는 것이 중요합니다",
  "꾸준한 연습이 실력 향상의 지름길입니다",
  "백스페이스보다는 정확하게 치는 연습을 하세요",
  "글쇠 익히기부터 차근차근 시작해 봅시다",
  "자신감을 가지고 천천히 타이핑해 보세요",
  "올바른 타자법은 문서 작업의 생산성을 높여줍니다",
  "눈은 화면에 두고 손가락은 자판을 찾게 하세요",
  "반복되는 연습이 실수를 줄여주는 최고의 방법입니다",
  "한글 두벌식 자판이 가장 보편적으로 사용됩니다",
  "타자 속도보다 정확도에 집중하는 것이 좋습니다",
  "오늘의 작은 성취가 내일의 큰 자신감이 됩니다",
  "꾸준히 노력하면 못할 일이 없습니다",
  "하루에 한 문장씩 연습해도 큰 변화가 생깁니다",
  "바른 자세가 바른 타자를 만듭니다",
  "타이핑은 생각을 표현하는 도구입니다",
  "느리더라도 확실하게 나아가는 것이 중요합니다",
  "매일 같은 시간에 연습하는 것이 효과적입니다",
  "손가락의 움직임이 자연스러워질 때까지 반복하세요",
  "글자를 외우지 말고 손이 기억하게 만드세요",
  "좋은 타자 실력은 디지털 시대의 필수 무기입니다",
  "집중력을 유지하면 타자 속도가 저절로 빨라집니다",
  "처음부터 완벽할 필요는 없습니다 꾸준함이 답입니다",
  "올바른 타자 습관은 평생 가는 자산이 됩니다",
  "급하게 치지 말고 정확하게 치는 연습을 먼저 하세요",
  "자판 위의 손가락 위치를 항상 의식하면서 타이핑하세요",
  "타자 연습도 결국 인내심과 집중력의 싸움입니다",
  "실수했다고 좌절하지 말고 천천히 다시 시작하세요",
  "자신의 타자 속도를 기록하며 성장 과정을 확인하세요",
  "올바른 타자법은 손목 건강에도 큰 도움이 됩니다",
  "타자 실력은 취업과 업무 효율에 직접적인 영향을 줍니다",
  "하루 십 분만 투자해도 일 년이면 큰 발전이 있습니다",
  "손가락이 자판을 기억할 때까지 꾸준히 반복하세요",
  "정확하지 않은 타자는 결국 시간 낭비입니다",
  "천재는 노력하는 사람을 이길 수 없습니다",
  "작은 습관이 모여 큰 실력을 만듭니다",
  "아무리 바빠도 하루에 한 번은 타이핑 연습을 합시다",
  "손가락의 힘을 빼고 부드럽게 타이핑하는 것이 중요합니다",
  "올바른 타자는 문서 작업의 피로도를 줄여줍니다",
  "백 스페이스를 누르는 시간도 아껴야 합니다",
  "타자 연습은 뇌와 손의 협응력을 길러줍니다",
  "정확한 타자는 전문가의 첫걸음입니다",
  "자신만의 타자 리듬을 찾는 것이 중요합니다",
  "눈으로 읽고 손으로 치는 과정을 반복하세요",
  "문장 단위로 끊어서 치는 연습을 해보세요",
  "손가락 위치를 고정하고 최소한의 움직임으로 타이핑하세요",
  "타자가 빨라지면 생각의 속도도 따라갑니다",
  "글을 쓰는 속도가 생각을 따라잡을 때가 가장 짜릿합니다",
  "무심코 치는 습관보다 의식적인 연습이 더 중요합니다",
  "손목 스트레칭과 함께 타자 연습을 병행하세요",
  "타이핑 속도보다 문서의 내용이 더 중요합니다",
  "바른 타자는 단순한 기술이 아니라 예술입니다",
  "도전하지 않으면 성장도 없습니다",
  "가장 늦었다고 생각할 때가 가장 빠른 때입니다",
  "오늘의 노력이 내일의 실력으로 이어집니다",
  "실패는 성공을 위한 가장 좋은 교과서입니다",
  "끝까지 포기하지 않는 사람이 결국 이깁니다",
  "자신을 믿고 꾸준히 나아가면 목표에 도달합니다",
  "모든 전문가는 한때 초보자였습니다",
  "작은 성공이 모여 큰 성취를 만듭니다",
  "타자 연습도 결국 습관의 힘이 가장 중요합니다",
  "한 글자 한 글자 정성을 다해 입력해보세요",
  "디지털 시대의 기본 소양은 바로 타자 실력입니다",
  "꾸준한 연습은 지루하지만 그 결실은 달콤합니다",
  "오늘도 한 문장씩 꾸준히 실력을 쌓아가세요",
  "타이핑은 생각을 현실로 만드는 마법 같은 도구입니다",
  "자판 위의 손가락 춤을 즐길 수 있을 때까지 연습하세요",
  "올바른 타자법을 익히면 컴퓨터 작업이 편안해집니다",
  "자신의 페이스를 유지하며 천천히 나아가세요",
  "타자 연습은 단순하지만 가장 효과적인 자기 개발입니다",
  "올바른 습관을 들이면 실력은 자연스럽게 따라옵니다",
  "하루 이틀 만에 이루어지는 것은 아무것도 없습니다",
  "작은 노력이 쌓여 큰 변화를 만들어냅니다",
  "자신의 타자 실력을 객관적으로 측정하고 개선하세요",
  "타자 연습은 꾸준함이 재능을 이깁니다",
  "매일 조금씩 나아지고 있다는 사실에 집중하세요",
  "손가락이 기억하는 순간 타자는 무의식적인 행동이 됩니다",
  "글쓰기와 타자는 별개의 기술이 아니라 함께 발전합니다",
  "올바른 타자법을 배우는 데 늦은 때는 없습니다",
  "시간을 정해두고 집중해서 연습하는 것이 효과적입니다",
  "자판을 바라보지 않고 타자하는 습관을 길러보세요",
  "한글 타자도 영어 타자처럼 꾸준히 연습해야 늡니다",
  "똑같은 문장을 여러 번 쳐보면 속도가 붙습니다",
  "자신에게 맞는 연습 방법을 찾는 것이 중요합니다",
  "타이핑 게임을 통해 즐겁게 실력을 키울 수 있습니다",
  "꾸준함은 재능을 이기고 노력은 운명을 바꿉니다",
  "오늘도 힘차게 타이핑을 시작해보세요",
];
