export const ENGLISH = [
  "The quick brown fox jumps over the lazy dog",
  "Practice makes perfect every single day",
  "Typing is a valuable skill in the modern world",
  "Never stop learning and improving yourself",
  "The sun sets in the west and rises in the east",
  "A journey of a thousand miles begins with a single step",
  "Stay focused on your goals and dreams",
  "Every moment is a fresh beginning in life",
  "The best time to plant a tree was twenty years ago",
  "Success is the sum of small efforts repeated daily",
  "Reading books expands your mind and vocabulary",
  "Technology changes the way we live and work",
  "Creativity is intelligence having fun",
  "The early bird catches the worm every morning",
  "Simple things often bring the greatest happiness",
  "Learning to code opens up endless possibilities",
  "A positive attitude makes a big difference",
  "The future belongs to those who prepare for it",
  "Good things come to those who work hard",
  "Every expert was once a beginner just like you",
  "Take a deep breath and type each word carefully",
  "Consistency matters more than perfection always",
  "The only way to do great work is to love what you do",
  "Small daily improvements lead to big results",
  "Your fingers will get faster with regular practice",
  "Mistakes are proof that you are trying your best",
  "The secret of getting ahead is getting started",
  "Believe in yourself and all that you are capable of",
  "Patience and persistence can achieve the impossible",
  "Type each word as it appears on the screen above",
  "Keep your eyes on the screen not on the keyboard",
  "Speed and accuracy will improve over time",
  "Focus on rhythm and flow while you type along",
  "Every keystroke brings you closer to mastery",
  "The journey of learning never truly ends at all",
  "Wake up each morning with a determined attitude",
  "Let your fingers dance across the keyboard today",
  "Turn your face to the sun and the shadows fall behind",
  "Act as if what you do makes a difference it does",
  "What lies behind us and before us are tiny matters",
  "The only limit to our realization of tomorrow is doubt",
  "Do what you can with all you have wherever you are",
  "It does not matter how slowly you go as long as you go",
  "Quality means doing it right when no one is looking",
  "In the middle of every difficulty lies opportunity",
  "The mind is everything what you think you become",
  "Nothing is impossible the word itself says I am possible",
  "Happiness is not something ready made it comes from action",
  "Life is what happens when you are busy making other plans",
  "Your time is limited so do not waste it living a borrowed life",
];

export const KOREAN = [
  "지금부터 천천히 한글 문장을 입력해보세요",
  "타자 연습은 꾸준함이 가장 중요합니다",
  "오늘도 좋은 하루 보내시길 바랍니다",
  "모든 위대한 일에는 작은 시작이 있습니다",
  "노력 없이 얻을 수 있는 결과는 없습니다",
  "컴퓨터 자판을 익히는 것은 생각보다 쉽습니다",
  "올바른 손가락 위치가 빠른 타자의 비결입니다",
  "천천히 정확하게 치는 것이 더 중요합니다",
  "자신의 타자 속도에 너무 연연하지 마세요",
  "매일 조금씩 연습하면 실력이 늘어납니다",
  "화면을 보면서 타자하는 습관을 길러보세요",
  "오타가 나도 괜찮습니다 계속 연습하세요",
  "한글 문서를 작성할 때 타자 실력이 빛을 발합니다",
  "올바른 자세로 앉아서 타자 연습을 해보세요",
  "손목에 무리가 가지 않도록 주의해야 합니다",
  "처음에는 느리더라도 포기하지 않는 것이 중요합니다",
  "꾸준한 연습이 실력 향상의 지름길입니다",
  "백스페이스보다는 정확하게 치는 연습을 하세요",
  "글쇠 익히기부터 차근차근 시작해 봅시다",
  "자신감을 가지고 천천히 타이핑해 보세요",
  "올바른 타자법은 문서 작업의 생산성을 높여줍니다",
  "눈은 화면에 두고 손가락은 자판을 찾게 하세요",
  "반복되는 연습이 실수를 줄여주는 최고의 방법입니다",
  "한글 두벌식 자판이 가장 보편적으로 사용됩니다",
  "타자 속도보다 정확도에 집중하는 것이 좋습니다",
];
